import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import ReactQueryProvider from "@/components/providers/react-query-provider";
import { ReactQueryDevtools } from "@tanstack/react-query-devtools";
import { Toaster } from "@/components/ui/sonner";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn(inter.className, 'w-full min-h-screen bg-[#ECECEC] text-black flex flex-col items-center')}>
        <ReactQueryProvider>
          <ReactQueryDevtools initialIsOpen={false} />
          <Toaster theme="light" richColors={true} />
          {children}
        </ReactQueryProvider>
      </body>
    </html>
  );
}
